name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - run: yarn install
    - run: yarn build
      env:
        NODE_ENV: test
    - run: yarn test-ci
      env:
        NODE_ENV: test
